# Generated by Django 3.2.7 on 2021-09-11 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_task_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='phone',
        ),
    ]
